/**
 * Cloudinary image URLs for all site assets.
 * Auto-generated by scripts/upload-images.mjs — do not edit manually.
 * To add new images: add to /public/images then re-run: node scripts/upload-images.mjs
 */

const BASE = "https://res.cloudinary.com/dqunwksxz/image/upload";

// Optimisation transformation — auto quality + format, serve WebP/AVIF automatically
const OPT = "f_auto,q_auto";

function url(path: string) {
  return `${BASE}/${OPT}/${path}`;
}

export const CLOUD_IMAGES = {
  about:       url("v1781270549/vhc-site/about.jpg"),
  drAman:      url("v1781270551/vhc-site/Dr-Aman.jpg"),
  drRavi:      url("v1781270553/vhc-site/Dr-Ravi.jpg"),
  inside:      url("v1781270569/vhc-site/inside.jpg"),
  logo:        url("v1781270570/vhc-site/logo.png"),
  medicines1:  url("v1781270572/vhc-site/medicines/1.jpg"),
  medicines2:  url("v1781270573/vhc-site/medicines/2.jpg"),
  outside:     url("v1781270575/vhc-site/outside.jpg"),
  prescription:url("v1781270576/vhc-site/prescription.jpg"),

  // Health campaign — Hinauli
  hinauli: [
    url("v1781270554/vhc-site/health-campaign/Hinauli/WhatsApp-Image-2026-06-05-at-9-25-13-PM.jpg"),
    url("v1781270558/vhc-site/health-campaign/Hinauli/WhatsApp-Image-2026-06-05-at-9-25-14-PM.jpg"),
    url("v1781270555/vhc-site/health-campaign/Hinauli/WhatsApp-Image-2026-06-05-at-9-25-14-PM-1-.jpg"),
    url("v1781270557/vhc-site/health-campaign/Hinauli/WhatsApp-Image-2026-06-05-at-9-25-14-PM-2-.jpg"),
    url("v1781270559/vhc-site/health-campaign/Hinauli/WhatsApp-Image-2026-06-05-at-9-25-15-PM.jpg"),
    url("v1781270561/vhc-site/health-campaign/Hinauli/WhatsApp-Image-2026-06-05-at-9-25-16-PM.jpg"),
    url("v1781270563/vhc-site/health-campaign/Hinauli/WhatsApp-Image-2026-06-05-at-9-25-17-PM.jpg"),
    url("v1781270562/vhc-site/health-campaign/Hinauli/WhatsApp-Image-2026-06-05-at-9-25-17-PM-1-.jpg"),
    url("v1781270567/vhc-site/health-campaign/Hinauli/WhatsApp-Image-2026-06-05-at-9-25-18-PM.jpg"),
    url("v1781270565/vhc-site/health-campaign/Hinauli/WhatsApp-Image-2026-06-05-at-9-25-18-PM-1-.jpg"),
    url("v1781270566/vhc-site/health-campaign/Hinauli/WhatsApp-Image-2026-06-05-at-9-25-18-PM-2-.jpg"),
  ],
} as const;
